import { useMetaTags } from "../hooks/useMetaTags";

const CLIENTS = [
    "A1",
    "ABB",
    "ADEL",
    "AFEA (Greace)",
    "Agencija Promo",
    "Alta Invest",
    "AVI Agencija vrhunskih idej",
    "Avtenta",
    "Avtohiša Berus",
    "Banka Slovenije",
    "Baustoff + Metall",
    "Biotehniška fakulteta",
    "Bold project",
    "Bolnica Topolšica",
    "Bosch Rexroth Slovenija",
    "BTS Company",
    "Caffe Central Portorož",
    "CD Cankarjev dom",
    "Casino Larix",
    "Cometal",
    "Center interesnih dejavnosti Ptuj",
    "Conections way",
    "Dekon",
    "Delavski dom Trbovlje",
    "Društvo vinogradnikov Črnomelj",
    "Dveri Pax dvorec Jarenina",
    "Dvorec Zemono",
    "ECE",
    "Elite Travel",
    "EMMA",
    "Europapier",
    "Eventisi",
    "FABulatorij",
    "Fakulteta za računalništvo in informatiko",
    "Fakulteta za elektrotehniko",
    "Filozofska fakulteta",
    "Festivalna dvorana",
    "FIBA Europe",
    "Fotona",
    "Gabriel Aluminium",
    "Gastro hematološka ambulanta",
    "Golf Bled",
    "Good4you",
    "Gospodarska zbornica Slovenije",
    "Gospodarsko razstavišče",
    "Grad Sevnica",
    "Grand hotel Bernardin",
    "Grand hotel Portorož",
    "Grand hotel Toplice Bled",
    "Grand hotel Union",
    "GRAWE zavarovalnica",
    "GS1 Slovenija",
    "GZS Gospodarska zbornica Slovenije",
    "Hiša Vizij",
    "Hotel Kempinsky Palace Portorož",
    "Hotel Slon",
    "Hyla",
    "Huawei",
    "IBE",
    "IBM",
    "Ingram Micro",
    "Inštitut za bioresonanco",
    "IPF",
    "Iskraemeco",
    "Iskratel",
    "Istrabenz Turizem",
    "JB restavracija",
    "Jezeršek gostinstvo",
    "JSKD – Javni sklad RS za kulturne dejavnosti",
    "Jub barve",
    "Kaval group",
    "Kekčeva domačija",
    "KGZS Kmetijsko gozdarska zbornica Slovenije",
    "Knauf Insulation",
    "Kobal transporti",
    "Kongresni center Brdo pri Kranju",
    "Konzulat republike Avstrije",
    "Krka",
    "Lek",
    "Liberty",
    "LIFE",
    "LoginEKO",
    "Ljubljanske mlekarne",
    "Luna",
    "Medex",
    "Merck Sharp & Dohme",
    "Mercator",
    "Ministrstvo za delo, družino, socialne razmere in enake možnosti",
    "Ministrstvo za okolje, podnebje in energijo",
    "Mitol",
    "Mojedelo.com",
    "MOL",
    "Mons",
    "Nil komunikacije",
    "Nika records",
    "NLB – Nova ljubljanska banka",
    "Novartis",
    "Občina Ankaran",
    "Občina Bled",
    "Občina Črnomelj",
    "Občina Kranj",
    "Občina Medvode",
    "Občina Metlika",
    "Občina Ribnica",
    "Občina Škofljica",
    "Odvetniška družba Rojs, Peljhan, Prelesnik in partnerji",
    "Odvetniška zbornica Slovenije",
    "Območna obrtna zbornica Ljubljana",
    "Obrtno podjetniška zbornica",
    "Oftalmološka klinika",
    "Omega Air",
    "Onkološki inštitut",
    "OnSite",
    "Osnovna šola Škofljica",
    "Penine Istenič",
    "Pernod Ricard",
    "Pirana",
    "Piranske soline",
    "Pivovarna Laško",
    "Poanta",
    "Polident",
    "POP TV",
    "Poslovni mediji",
    "Postonjska jama",
    "Predsedovanje EU 2021",
    "Pristop",
    "Protokol Slovenije",
    "Radio Ognjišče",
    "Radio Univox",
    "Regia group",
    "Reitenburg",
    "Roche",
    "Roletarstvo Medle",
    "RTV Slovenija",
    "Sandoz",
    "Sava turizem",
    "Sberbank",
    "SIJ Slovenska industrija jekla",
    "Simobil",
    "SIW – Slovenian incoming workshop",
    "Slovenske železnice",
    "SMK – Slovenska marketinška konferenca",
    "Slovensko društvo Informatika",
    "Sparkasse banka",
    "Superbrands",
    "STO – Slovenska tiskovna organizacija",
    "Studio Marketing",
    "Studio Terminal",
    "Tax-fin-lex",
    "Teater",
    "Teater Serpentes",
    "Tehnološki park Ljubljana",
    "Telekom Slovenija",
    "TEM Čatež",
    "Terme Olimia",
    "Thermana Laško",
    "Tilia estate",
    "TKK",
    "TRM Filter",
    "Turistična zveza Slovenije",
    "Turizem Bohinj",
    "Turizem Bled",
    "Turizem Kranjska Gora",
    "TV Koper",
    "UKC Ljubljana",
    "UKC Maribor",
    "Univerza v Ljubljani",
    "Uprava RS za izvrševanje kazenskih sankcij",
    "Uprava RS za zaščito in reševanje",
    "Vibecraft agencija",
    "Vila Bled",
    "Vinakoper",
    "Visit Ljubljana",
    "Visit Rado’ca",
    "Visit Opatija",
    "Volvo Renault trucks",
    "Warehouse collective produkcija",
    "Zadružna zveza Slovenije",
    "Zavarovalnica Generali",
    "Zavod za kulturo, turizem, šport in mladino Metlika",
    "Zavod za turizem, kulturo in šport Kamnik",
    "Zdravniška zbornica Slovenije",
    "Združenje Manager",
    "Zlata piščal",
    "ZPIZ",
    "4 Points by Sheraton",
    "500 podjetnic"
];

export default function Clients() {
    useMetaTags({
        title: "Reference",
        description: "Organizacije in podjetja, ki jim je Zasedba Kranjci že pomagala ustvariti nepozabne dogodke.",
        path: "/clients"
    });
    return (
        <div class="container">
            <h1>Reference</h1>
            <p>
                Reference nekaterih vidnejših partnerjev, ki so nam večkrat zaupali glasbeno obogatitev poslovnega dogodka.
                Vaša odločitev je za nas dodatna motivacija, da se naslednjič vrnemo še boljši.
            </p>
            <p style="font-style: italic;">Seznam se sproti dopolnjuje in spreminja.</p>
            <ul class="clients-list">
                {CLIENTS.map((client) => (
                    <li key={client}>{client}</li>
                ))}
            </ul>
        </div>
    );
}
