// Auto-generated by scripts/fetch-shows.mjs
import { markdownToHtml } from "../utils/markdown";

export type Show = {
    date: string;
    city: string;
    venue: string;
    more: string;
    time: string;
    type: "open" | "closed";
    link?: string;
};

const RAW_SHOWS: Show[] = [
    {
        "date": "2025-11-28",
        "city": "Ljubljana",
        "venue": "eVino",
        "more": "Prednovoletna zabava **Happy Gym**. Z Nami bo pevka Tanja Srednik.",
        "time": "20:00",
        "type": "closed"
    },
    {
        "date": "2025-11-30",
        "city": "Radovljica",
        "venue": "Radovljica",
        "more": "Koncert ob prižigu lučk. Z Nami bo pevka Anea Mlinar.",
        "time": "17:00",
        "type": "open"
    },
    {
        "date": "2025-12-05",
        "city": "Ljubljana",
        "venue": "Dvorni bar",
        "more": "Novoletna zabava **Odvetniške pisarne Senica** in koncert zasedbe Kranjci. Z Nami bo pevka Anea Mlinar.",
        "time": "21:30",
        "type": "closed"
    },
    {
        "date": "2025-12-12",
        "city": "Ljubljana",
        "venue": "Hotel Mons",
        "more": "Novoletna zabava podjetja **Novartis**. Z Nami bo pevka Anea Mlinar.",
        "time": "18:00",
        "type": "closed"
    },
    {
        "date": "2025-12-13",
        "city": "Ljubljana - Škofljica",
        "venue": "Občina Škofljica",
        "more": "Novoletna zabava in koncert zasedbe Kranjci. Z Nami bo pevka Anea Mlinar.",
        "time": "20:00",
        "type": "open"
    }
];

export const shows: Show[] = RAW_SHOWS.map((show) => ({
    ...show,
    more: markdownToHtml(show.more)
}));
