// Auto-generated by scripts/fetch-shows.mjs
import { markdownToHtml } from "../utils/markdown";

export type Show = {
    date: string;
    city: string;
    venue: string;
    more: string;
    time: string;
    type: "open" | "closed";
    link?: string;
};

const RAW_SHOWS: Show[] = [
    {
        "date": "2025-11-28",
        "city": "Ljubljana",
        "venue": "eVino",
        "more": "Prednovoletna zasebna zabava. 🎉 🎶",
        "time": "20:00",
        "type": "closed"
    },
    {
        "date": "2025-11-30",
        "city": "Radovljica",
        "venue": "Radovljica",
        "more": "Koncert ob prižigu lučk v Radovljici.",
        "time": "17:00",
        "type": "open"
    },
    {
        "date": "2025-12-05",
        "city": "Ljubljana",
        "venue": "Dvorni bar",
        "more": "Novoletna zabava **Odvetniške pisarne Senica** in koncert zasedbe Kranjci. Z Nami bo pevka Anea Mlinar.",
        "time": "21:30",
        "type": "closed"
    }
];

export const shows: Show[] = RAW_SHOWS.map((show) => ({
    ...show,
    more: markdownToHtml(show.more)
}));
